###############################################################################
#  Repository: ${REPOSITORY}/mucoll-sim
#  Tag:        ${VERSION}-alma9
###############################################################################

ARG VERSION=release
ARG REPOSITORY=infnpd
FROM ${REPOSITORY}/mucoll-spack:${VERSION}-alma9

# Adding repositories: Key4hep + MuColl
ARG KEY4HEP_COMMIT=dc0b2bc4aaad8f3ef5f3c7f62ff5b0277a554eee

RUN source /opt/setup_spack.sh && \
    REPOPATH=${SPACK_ROOT}/var/key4hep-spack && \
    git clone https://github.com/key4hep/key4hep-spack ${REPOPATH} && \
    if [ -n "${KEY4HEP_COMMIT}" ]; then \
      cd ${REPOPATH}; \
      git checkout ${KEY4HEP_COMMIT}; \
    fi

# Apply our patches to spack
COPY apply_patches.sh ./apply_patches.sh
RUN source /opt/setup_spack.sh && \
    ./apply_patches.sh ${SPACK_ROOT}/var/key4hep-spack

# Add the package repositories
RUN source /opt/setup_spack.sh && \
    spack repo add --scope system ${SPACK_ROOT}/var/key4hep-spack

# Create the release environment
RUN source /opt/setup_spack.sh && \
    spack env create k4base && \
    spack env activate k4base && \
    cp ${SPACK_ROOT}/var/key4hep-spack/environments/key4hep-common/*.yaml ${SPACK_ENV} && \
    cp ${SPACK_ROOT}/var/key4hep-spack/environments/key4hep-release/spack.yaml ${SPACK_ENV} && \
    echo "source /opt/setup_spack.sh" > ${HOME}/setup_env.sh && \
    echo "spack env activate k4base" >> ${HOME}/setup_env.sh && \
    echo "spack env status" >> ${HOME}/setup_env.sh

# Concretizing the Key4hep stack reusing system packages as external
RUN source ${HOME}/setup_env.sh && \
    spack add key4hep-stack && \
    spack concretize --reuse

# Installing fragments of dependency tree in separate layers for cached debugging
ENV SPACK_INSTALL_OPTS "--only-concrete --no-add --fail-fast"

RUN source ${HOME}/setup_env.sh && \
    spack spec -NIt && \
    spack install ${SPACK_INSTALL_OPTS} && \
    spack clean -a

RUN source ${HOME}/setup_env.sh && \
    echo "source ${SPACK_ENV}/.spack-env/view/setup.sh" > /opt/setup_key4hep.sh && \
    echo "alias setup_key4hep=\"source /opt/setup_key4hep.sh\"" >> /etc/profile.d/aliases.sh

# Setting up users to be used for the local environment setup
RUN useradd --shell /bin/bash --create-home mucoll
USER mucoll
WORKDIR /home/mucoll

ENTRYPOINT ["/bin/bash", "--login"]

